kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: container
          image: registry.redhat.io/rhel9/postgresql-13
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              value: microsweeper
            - name: POSTGRESQL_PASSWORD
              value: microsweeper
            - name: POSTGRESQL_DATABASE
              value: microsweeper
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: Recreate

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
